/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomMenuBar: typeof import('./src/components/BottomMenuBar.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileComponent: typeof import('./src/components/FileComponent.vue')['default']
    FileIcon: typeof import('./src/components/FileIcon.vue')['default']
    FileInfoView: typeof import('./src/components/FileInfoView.vue')['default']
    FilePreview: typeof import('./src/components/FilePreview.vue')['default']
    FluentAppsList24Regular: typeof import('~icons/fluent/apps-list24-regular')['default']
    FluentArrowLeft24Regular: typeof import('~icons/fluent/arrow-left24-regular')['default']
    FluentArrowSync24Regular: typeof import('~icons/fluent/arrow-sync24-regular')['default']
    FluentArrowUpload24Filled: typeof import('~icons/fluent/arrow-upload24-filled')['default']
    FluentCloudDownload24Filled: typeof import('~icons/fluent/cloud-download24-filled')['default']
    FluentCommentText24Filled: typeof import('~icons/fluent/comment-text24-filled')['default']
    FluentDismiss24Regular: typeof import('~icons/fluent/dismiss24-regular')['default']
    FluentDocument24Filled: typeof import('~icons/fluent/document24-filled')['default']
    FluentdocumentAdd24Filled: typeof import('~icons/fluent/document-add24-filled')['default']
    FluentDocumentAdd24Filled: typeof import('~icons/fluent/document-add24-filled')['default']
    FluentDocumentTable24Filled: typeof import('~icons/fluent/document-table24-filled')['default']
    FluentfolderAdd24Filled: typeof import('~icons/fluent/folder-add24-filled')['default']
    FluentFolderOpen24Filled: typeof import('~icons/fluent/folder-open24-filled')['default']
    FluentFolderZip24Filled: typeof import('~icons/fluent/folder-zip24-filled')['default']
    FluentGrid24Regular: typeof import('~icons/fluent/grid24-regular')['default']
    FluentImage24Regular: typeof import('~icons/fluent/image24-regular')['default']
    FluentInfo24Filled: typeof import('~icons/fluent/info24-filled')['default']
    FluentMusicNote2Play20Filled: typeof import('~icons/fluent/music-note2-play20-filled')['default']
    FluentRename24Filled: typeof import('~icons/fluent/rename24-filled')['default']
    FluentSearch24Regular: typeof import('~icons/fluent/search24-regular')['default']
    FluentVideoClip24Filled: typeof import('~icons/fluent/video-clip24-filled')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
